CompileFlags:
  Add:
    - --include-directory=/usr/include
    - --include-directory=/usr/include/x86_64-linux-gnu
    - --include-directory=/usr/include/c++/12
    - --include-directory=/usr/include/x86_64-linux-gnu/c++/12
